version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5050
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5050
